var u={
    Name:"Keerthi",
    Age:26,
    Group:"BD2S"
};
for (var i in u){
    console.log(i,u[i]);
    
document.write(i,u[i]);
}

var gokul={
    Name:"J.GOKULAKRISHNAN",
    DOB: "12.09.2001",
    E_mail: "GOKULAKRISHNAN252@GMAIL.COM",
    Address: "Porur Chennai-116",
    Phone:6374938411,
    Education:"B.COM",
    Skills:"MS Office",
    Strengths:"Good Listener,Punctuality,Motivater",
    Language_Known: "Tamil,English",
    Status:"Unmarried",
    Gender: "Male",
    Hobbies: "Cricket,Listening Music",

};
console.log(JSON.stringify(gokul));

document.write(JSON.stringify(gokul));